### ISSUE TITLE
That's how bugs should be created!

### ISSUE THREAD

**Issue by grundic** [tomnis/teamcity-junit#1]
Occasionally found your repo, respect!
I think after such bug report issue should be fixed very soon :)
One small note: you can add  a link to corresponding issue in Teamcity bug tracker.

Good luck!

**Comment by tomnis** [comment]
Thanks! I haven't submitted a ticket to jetbrains just yet, but i'll update this repo with the link :)

**Comment by grundic** [comment]
:thumbsup:
